<?php

use Illuminate\Database\Seeder;

class GroupSeeder extends Seeder
{
    public function run()
    {
        $typi_groups = [
            ['id' => '1', 'name' => 'Administrator', 'permissions' => '{"user.updatepreferences":"1","history":"1","dashboard":"1","settings.index":"1","blocks.index":"1","blocks.show":"1","blocks.create":"1","blocks.store":"1","blocks.edit":"1","blocks.update":"1","blocks.sort":"1","blocks.destroy":"1","categories.index":"1","categories.show":"1","categories.create":"1","categories.store":"1","categories.edit":"1","categories.update":"1","categories.sort":"1","categories.destroy":"1","contacts.index":"1","contacts.show":"1","contacts.create":"1","contacts.store":"1","contacts.edit":"1","contacts.update":"1","contacts.sort":"1","contacts.destroy":"1","events.index":"1","events.show":"1","events.create":"1","events.store":"1","events.edit":"1","events.update":"1","events.sort":"1","events.destroy":"1","files.index":"1","files.show":"1","files.create":"1","files.store":"1","files.edit":"1","files.update":"1","files.sort":"1","files.destroy":"1","galleries.index":"1","galleries.show":"1","galleries.create":"1","galleries.store":"1","galleries.edit":"1","galleries.update":"1","galleries.sort":"1","galleries.destroy":"1","groups.index":"1","groups.show":"1","groups.create":"1","groups.store":"1","groups.edit":"1","groups.update":"1","groups.sort":"1","groups.destroy":"1","menus.index":"1","menus.show":"1","menus.create":"1","menus.store":"1","menus.edit":"1","menus.update":"1","menus.sort":"1","menus.destroy":"1","news.index":"1","news.show":"1","news.create":"1","news.store":"1","news.edit":"1","news.update":"1","news.sort":"1","news.destroy":"1","pages.index":"1","pages.show":"1","pages.create":"1","pages.store":"1","pages.edit":"1","pages.update":"1","pages.sort":"1","pages.destroy":"1","partners.index":"1","partners.show":"1","partners.create":"1","partners.store":"1","partners.edit":"1","partners.update":"1","partners.sort":"1","partners.destroy":"1","projects.index":"1","projects.show":"1","projects.create":"1","projects.store":"1","projects.edit":"1","projects.update":"1","projects.sort":"1","projects.destroy":"1","slides.index":"1","slides.show":"1","slides.create":"1","slides.store":"1","slides.edit":"1","slides.update":"1","slides.sort":"1","slides.destroy":"1","tags.index":"1","tags.show":"1","tags.create":"1","tags.store":"1","tags.edit":"1","tags.update":"1","tags.sort":"1","tags.destroy":"1","translations.index":"1","translations.show":"1","translations.create":"1","translations.store":"1","translations.edit":"1","translations.update":"1","translations.sort":"1","translations.destroy":"1","users.index":"1","users.show":"1","users.create":"1","users.store":"1","users.edit":"1","users.update":"1","users.sort":"1","users.destroy":"1"}', 'created_at' => '2014-11-04 23:30:06', 'updated_at' => '2014-11-04 23:30:06'],
            ['id' => '2', 'name' => 'Redactor', 'permissions' => '{"user.updatepreferences":"1","history":"1","dashboard":"1","settings.index":"1","blocks.index":"1","blocks.show":"1","blocks.create":"1","blocks.store":"1","blocks.edit":"1","blocks.update":"1","categories.index":"1","categories.show":"1","categories.create":"1","categories.store":"1","categories.edit":"1","categories.update":"1","contacts.index":"1","contacts.show":"1","contacts.create":"1","contacts.store":"1","contacts.edit":"1","contacts.update":"1","events.index":"1","events.show":"1","events.create":"1","events.store":"1","events.edit":"1","events.update":"1","files.index":"1","files.show":"1","files.create":"1","files.store":"1","files.edit":"1","files.update":"1","galleries.index":"1","galleries.show":"1","galleries.create":"1","galleries.store":"1","galleries.edit":"1","galleries.update":"1","groups.index":"1","groups.show":"1","groups.create":"1","groups.store":"1","groups.edit":"1","groups.update":"1","menus.index":"1","menus.show":"1","menus.create":"1","menus.store":"1","menus.edit":"1","menus.update":"1","news.index":"1","news.show":"1","news.create":"1","news.store":"1","news.edit":"1","news.update":"1","pages.index":"1","pages.show":"1","pages.create":"1","pages.store":"1","pages.edit":"1","pages.update":"1","partners.index":"1","partners.show":"1","partners.create":"1","partners.store":"1","partners.edit":"1","partners.update":"1","projects.index":"1","projects.show":"1","projects.create":"1","projects.store":"1","projects.edit":"1","projects.update":"1","slides.index":"1","slides.show":"1","slides.create":"1","slides.store":"1","slides.edit":"1","slides.update":"1","tags.index":"1","tags.show":"1","tags.create":"1","tags.store":"1","tags.edit":"1","tags.update":"1","translations.index":"1","translations.show":"1","translations.create":"1","translations.store":"1","translations.edit":"1","translations.update":"1","users.index":"1","users.show":"1","users.create":"1","users.store":"1","users.edit":"1","users.update":"1"}', 'created_at' => '2014-11-04 23:30:06', 'updated_at' => '2014-11-04 23:30:06'],
        ];

        DB::table('groups')->insert($typi_groups);
    }
}
