<?php

use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    public function run()
    {
        $typi_permissions = [
            ['id' => 1, 'name' => 'change-locale', 'guard_name' => 'web'],
            ['id' => 2, 'name' => 'update-preferences', 'guard_name' => 'web'],
            ['id' => 3, 'name' => 'index-history', 'guard_name' => 'web'],
            ['id' => 4, 'name' => 'destroy-history', 'guard_name' => 'web'],
            ['id' => 5, 'name' => 'dashboard', 'guard_name' => 'web'],
            ['id' => 6, 'name' => 'index-settings', 'guard_name' => 'web'],
            ['id' => 7, 'name' => 'index-blocks', 'guard_name' => 'web'],
            ['id' => 8, 'name' => 'show-block', 'guard_name' => 'web'],
            ['id' => 9, 'name' => 'create-block', 'guard_name' => 'web'],
            ['id' => 10, 'name' => 'store-block', 'guard_name' => 'web'],
            ['id' => 11, 'name' => 'edit-block', 'guard_name' => 'web'],
            ['id' => 12, 'name' => 'update-block', 'guard_name' => 'web'],
            ['id' => 13, 'name' => 'sort-blocks', 'guard_name' => 'web'],
            ['id' => 14, 'name' => 'destroy-block', 'guard_name' => 'web'],
            ['id' => 15, 'name' => 'index-files', 'guard_name' => 'web'],
            ['id' => 16, 'name' => 'show-file', 'guard_name' => 'web'],
            ['id' => 17, 'name' => 'create-file', 'guard_name' => 'web'],
            ['id' => 18, 'name' => 'store-file', 'guard_name' => 'web'],
            ['id' => 19, 'name' => 'edit-file', 'guard_name' => 'web'],
            ['id' => 20, 'name' => 'update-file', 'guard_name' => 'web'],
            ['id' => 21, 'name' => 'sort-files', 'guard_name' => 'web'],
            ['id' => 22, 'name' => 'destroy-file', 'guard_name' => 'web'],
            ['id' => 23, 'name' => 'index-galleries', 'guard_name' => 'web'],
            ['id' => 24, 'name' => 'show-gallery', 'guard_name' => 'web'],
            ['id' => 25, 'name' => 'create-gallery', 'guard_name' => 'web'],
            ['id' => 26, 'name' => 'store-gallery', 'guard_name' => 'web'],
            ['id' => 27, 'name' => 'edit-gallery', 'guard_name' => 'web'],
            ['id' => 28, 'name' => 'update-gallery', 'guard_name' => 'web'],
            ['id' => 29, 'name' => 'sort-galleries', 'guard_name' => 'web'],
            ['id' => 30, 'name' => 'destroy-gallery', 'guard_name' => 'web'],
            ['id' => 31, 'name' => 'index-menus', 'guard_name' => 'web'],
            ['id' => 32, 'name' => 'show-menu', 'guard_name' => 'web'],
            ['id' => 33, 'name' => 'create-menu', 'guard_name' => 'web'],
            ['id' => 34, 'name' => 'store-menu', 'guard_name' => 'web'],
            ['id' => 35, 'name' => 'edit-menu', 'guard_name' => 'web'],
            ['id' => 36, 'name' => 'update-menu', 'guard_name' => 'web'],
            ['id' => 37, 'name' => 'sort-menus', 'guard_name' => 'web'],
            ['id' => 38, 'name' => 'destroy-menu', 'guard_name' => 'web'],
            ['id' => 39, 'name' => 'index-pages', 'guard_name' => 'web'],
            ['id' => 40, 'name' => 'show-page', 'guard_name' => 'web'],
            ['id' => 41, 'name' => 'create-page', 'guard_name' => 'web'],
            ['id' => 42, 'name' => 'store-page', 'guard_name' => 'web'],
            ['id' => 43, 'name' => 'edit-page', 'guard_name' => 'web'],
            ['id' => 44, 'name' => 'update-page', 'guard_name' => 'web'],
            ['id' => 45, 'name' => 'sort-pages', 'guard_name' => 'web'],
            ['id' => 46, 'name' => 'destroy-page', 'guard_name' => 'web'],
            ['id' => 47, 'name' => 'index-roles', 'guard_name' => 'web'],
            ['id' => 48, 'name' => 'show-role', 'guard_name' => 'web'],
            ['id' => 49, 'name' => 'create-role', 'guard_name' => 'web'],
            ['id' => 50, 'name' => 'store-role', 'guard_name' => 'web'],
            ['id' => 51, 'name' => 'edit-role', 'guard_name' => 'web'],
            ['id' => 52, 'name' => 'update-role', 'guard_name' => 'web'],
            ['id' => 53, 'name' => 'sort-roles', 'guard_name' => 'web'],
            ['id' => 54, 'name' => 'destroy-role', 'guard_name' => 'web'],
            ['id' => 55, 'name' => 'index-translations', 'guard_name' => 'web'],
            ['id' => 56, 'name' => 'show-translation', 'guard_name' => 'web'],
            ['id' => 57, 'name' => 'create-translation', 'guard_name' => 'web'],
            ['id' => 58, 'name' => 'store-translation', 'guard_name' => 'web'],
            ['id' => 59, 'name' => 'edit-translation', 'guard_name' => 'web'],
            ['id' => 60, 'name' => 'update-translation', 'guard_name' => 'web'],
            ['id' => 61, 'name' => 'sort-translations', 'guard_name' => 'web'],
            ['id' => 62, 'name' => 'destroy-translation', 'guard_name' => 'web'],
            ['id' => 63, 'name' => 'index-users', 'guard_name' => 'web'],
            ['id' => 64, 'name' => 'show-user', 'guard_name' => 'web'],
            ['id' => 65, 'name' => 'create-user', 'guard_name' => 'web'],
            ['id' => 66, 'name' => 'store-user', 'guard_name' => 'web'],
            ['id' => 67, 'name' => 'edit-user', 'guard_name' => 'web'],
            ['id' => 68, 'name' => 'update-user', 'guard_name' => 'web'],
            ['id' => 69, 'name' => 'sort-users', 'guard_name' => 'web'],
            ['id' => 70, 'name' => 'destroy-user', 'guard_name' => 'web'],
            ['id' => 71, 'name' => 'view-navbar', 'guard_name' => 'web'],
        ];

        DB::table('permissions')->insert($typi_permissions);
    }
}
