<?php

return [
    'types' => [
        'mp3' => 'a',
        'wav' => 'a',
        'aif' => 'a',
        'aiff' => 'a',
        'aac' => 'a',
        'mp4' => 'a',
        'wma' => 'a',
        'ogg' => 'a',
        'm4v' => 'v',
        'mkv' => 'v',
        'flv' => 'v',
        'mov' => 'v',
        'm4a' => 'v',
        'webm' => 'v',
        'ogv' => 'v',
        'xls' => 'd',
        'xlsx' => 'd',
        'doc' => 'd',
        'docx' => 'd',
        'pdf' => 'd',
        'txt' => 'd',
        'rtf' => 'd',
        'odt' => 'd',
        'ods' => 'd',
        'odp' => 'd',
        'odg' => 'd',
        'odc' => 'd',
        'odf' => 'd',
        'odb' => 'd',
        'odi' => 'd',
        'odm' => 'd',
        'zip' => 'd',
        'jpg' => 'i',
        'jpe' => 'i',
        'jpeg' => 'i',
        'png' => 'i',
        'gif' => 'i',
        'svg' => 'i',
    ],
];
