<?php
return array(

    'types' => array(
        'mp3'  => 'a',
        'wav'  => 'a',
        'aif'  => 'a',
        'aac'  => 'a',
        'm4v'  => 'v',
        'mkv'  => 'v',
        'flv'  => 'v',
        'mov'  => 'v',
        'mp4'  => 'v',
        'xls'  => 'd',
        'xlsx' => 'd',
        'doc'  => 'd',
        'docx' => 'd',
        'pdf'  => 'd',
        'txt'  => 'd',
        'rtf'  => 'd',
        'odt'  => 'd',
        'ods'  => 'd',
        'odp'  => 'd',
        'odg'  => 'd',
        'odc'  => 'd',
        'odf'  => 'd',
        'odb'  => 'd',
        'odi'  => 'd',
        'odm'  => 'd',
        'jpg'  => 'i',
        'jpeg' => 'i',
        'png'  => 'i',
        'gif'  => 'i',
    ),

);
